name: Publish pyogrio to PyPI / GitHub

on: [push]

jobs:
  build-n-publish:
    name: Build and publish pyogrio to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build a source tarball
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools
          python -m build --sdist

      - name: Get Asset name
        run: |
          export PKG=$(ls dist/ | grep tar)
          set -- $PKG
          echo "name=$1" >> $GITHUB_ENV

      - name: sdist
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/${{ env.name }}
